### ISSUE TITLE
The incident angle shouldn't be hardcoded

### ISSUE THREAD

**Issue by MilanKlausz** [MilanKlausz/mcstas_gisans#1]
**Issue:**
Currently the _alpha_inc_ incident angle is hardcoded in the BornAgain script. The incident angle is the result of the coordinate system rotation for the McStas MCPL output component (e.g.:  _ROTATED (89.760,0,0) RELATIVE sample_arm_ gives 0.24 deg incident angle), that is essentially the same as rotating the sample. (BornAgain works in a system where the sample surface is in the horisontal plane.)
There is no coordinate system rotation implemented for the incident neutrons in the BornAgain script so the incident angle is decided by the McStas simulation (output). 

In reality, the end of the guide system might have an angle (might not be horisontal), plus the sample could also be rotated (not be in the horisontal plane). Also, the detector surface is assumed to be perpendicular to the sample surface (which also might not be the case)

**Expectation**
The neutron parameters (position, direction) in the MCPL file should be expressed with respect to a flat sample in the horisontal plane. The coordinate rotation mimicing the sample rotation should be applied in the BornAgain script, based on the intended incident angle from a dedicated input and the guide end angle stored as an MCPL metadata. By default, the detector surface should be vertical, regardless of the sample rotation (incident angle), but there might as well be an input for detector tilt angle.

**Tasks**
- [ ] The neutron parameters in the MCPL file should be expressed with respect to a flat(liquid) sample. So rotate the MCPL output component in accordance with the angle of the guide end
- [ ] The angle of the guide end should be stored as metadata in the MCPL file
- [x] The incident angle should be an input value for the BornAgain script
- [x] Coordinate transformation should be applied to the incident neutrons in the BornAgain script to accound for the guide end angle and the virtual sample rotation (to get the intended incident angle in BornAgain's 'horisontal sample based' coordinate system)
- [ ] The detector surface should remain vertical, regardless of all angles.

**Comment by MilanKlausz** [comment]
Most of these issues has been addressed a long time ago. 
Currently the MCPL_output component is not rotated in McStas, the rotation (coordinate transformation) to get a certain alpha incident angle on the sample is done in the python script (so one McStas simulation can be used for multiple sample rotation simulations).

Up until the latest commit '[handle beam declination](https://github.com/MilanKlausz/mcstas_gisans/commit/6262e391346b726e0aba7633189175eb42e56c55)' , the detector surface was assumed to be perpendicular to the incident beam, but not the possible beam declination angle is taken into account. The detector surface is assumed to be vertical.
